### PR TITLE
error handle file creation

### PR DESCRIPTION
**Pull request by D3XX3R**
make lumen not crash when data folder already exists

### CODE REVIEW

**Comment by D3XX3R** [comment]
This was created right after 3e9006d. So it doesn't account for changes made after that.
The problem still stands. If the data folder already exists the script will panic.

**Comment by ChecksumDev** [comment]
I might have fixed this by accident in https://github.com/ChecksumDev/lumen/commit/ebaaa876f670a34e2c152ab8865ed232574290f2, I don't believe this has panic potential.

This change was done to work better with Docker as well as it just making more sense

**Comment by ChecksumDev** [comment]
I do believe the project's structure should now be stabilized for the time being, I'm very surprised to get a pull request so early on, sorry for the turbulence!

**Comment by D3XX3R** [comment]
I've seen this project on my GitHub home page and it looked very promising.
Looking forward to contribute if and when help is needed. 
Closing the pull request since this issue seems to be fixed.

**Pull request closed without merging**
